name: Binary Build
on:
  push:
    branches: '*'
  pull_request:
    branches: [master] # This allows us to test PRs without always needing to build locally. It's secure as all first time contributors first need to be approved for running GitHub actions
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13, macos-11, ARM64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/a95ed9fe764c3ba2bf2d2fa223012c379cd6b32e.tar.gz
    - uses: cachix/cachix-action@v12
      with:
        name: digitallyinduced
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: git clone https://github.com/digitallyinduced/ihp-boilerplate.git
    - name: Cache build directory
      uses: actions/cache@v2
      with:
        path: |
          ihp-boilerplate/build
        key: ${{ runner.os }}-ghc
    - run: |
          cd ihp-boilerplate
          php ../.github/patch-flakes.php ${{ github.ref }}
          cat default.nix
          mv Makefile Makefile.old
          echo 'GHC_OPTIONS+= -rtsopts=all\n.SHELLFLAGS := -eu -o pipefail -c\n\n'|cat - Makefile.old > Makefile
          nix-shell --run "new-application Web && make build/bin/RunUnoptimizedProdServer"
    - run: |
        cd ihp-boilerplate && nix develop --impure --command "true"
    # Also build the framework's dev env
    - name: Install devenv.sh
      run: nix profile install --accept-flake-config github:cachix/devenv/latest
      if: matrix.os != 'ARM64'
    - run: |
        devenv ci && devenv shell echo ok